//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Laboratori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Laboratori()
        {
            this.GrupiLabs = new HashSet<GrupiLab>();
            this.Totalis = new HashSet<Totali>();
        }
    
        public int Id { get; set; }
        public string Emri { get; set; }
        public string Lenda { get; set; }
        public int CikliStudimit { get; set; }
        public string Perriudha { get; set; }
        public int PedagoguId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GrupiLab> GrupiLabs { get; set; }
        public virtual Pedagogu Pedagogu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Totali> Totalis { get; set; }
    }
}
