//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LaboratoriesEntities : DbContext
    {
        public LaboratoriesEntities()
            : base("name=LaboratoriesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Dega> Degas { get; set; }
        public virtual DbSet<Fakulteti> Fakultetis { get; set; }
        public virtual DbSet<Grupi> Grupis { get; set; }
        public virtual DbSet<GrupiLab> GrupiLabs { get; set; }
        public virtual DbSet<Laboratori> Laboratoris { get; set; }
        public virtual DbSet<Pedagogu> Pedagogus { get; set; }
        public virtual DbSet<Studenti> Studentis { get; set; }
        public virtual DbSet<Tema> Temas { get; set; }
        public virtual DbSet<Totali> Totalis { get; set; }
        public virtual DbSet<Universiteti> Universitetis { get; set; }
        public virtual DbSet<Vleresimi> Vleresimis { get; set; }
    }
}
