//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tema
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tema()
        {
            this.Vleresimis = new HashSet<Vleresimi>();
        }
    
        public int Id { get; set; }
        public int GrupiLabId { get; set; }
        public int LaboratoriNr { get; set; }
        public System.DateTime Data { get; set; }
        public string Tema1 { get; set; }
        public int Vleresimi { get; set; }
    
        public virtual GrupiLab GrupiLab { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vleresimi> Vleresimis { get; set; }
    }
}
