//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratories.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Totali
    {
        public int Id { get; set; }
        public int Totali1 { get; set; }
        public int StudentiId { get; set; }
        public int LaboratoriId { get; set; }
    
        public virtual Laboratori Laboratori { get; set; }
        public virtual Studenti Studenti { get; set; }
    }
}
